In [1]:
import pandas as pd

In [2]:
"""
#On inverse les colonnes et les lignes pour joindre la target au dataset
df = pd.read_csv("abundance_matrix_80_85.RED.csv")
df_transposed = df.T
print(df_transposed.head())

"""

'\n#On inverse les colonnes et les lignes pour joindre la target au dataset\ndf = pd.read_csv("abundance_matrix_80_85.RED.csv")\ndf_transposed = df.T\nprint(df_transposed.head())\n\n'

In [3]:
df_80_85 = pd.read_csv("abundance_matrix_80_85.RED.csv")

In [4]:
#del df_80_85

In [5]:
df_metb_full = pd.read_csv("metdb_full_count_transcript_final_labelOK.csv")

In [6]:
df_80_85.dtypes

CC             object
METDB-00001     int64
METDB-00002     int64
METDB-00003     int64
METDB-00004     int64
                ...  
METDB-00481     int64
METDB-00482     int64
METDB-00483     int64
METDB-00484     int64
METDB-00486     int64
Length: 456, dtype: object

In [7]:
CC_80_85 = df_80_85["CC"] #On charge tous les CC dans une variable, afin de pouvoir identifier les colonnes sélectionnées par notre modèle, après .fit, avec .coef_

In [8]:
CC_80_85.shape

(1016112,)

In [9]:
df_80_85.index = df_80_85["CC"]
df_80_85.drop("CC", axis=1, inplace = True)

In [10]:
df_80_85.head()

METDB-00001  METDB-00002  METDB-00003  METDB-00004  METDB-00005  \
CC                                                                      
CC_0            1            0            0            0            0   
CC_1            1            0            0            0            1   
CC_2            3            0            0            0            0   
CC_3            1            0            0            0            0   
CC_4            1            0            0            0            0   

      METDB-00006  METDB-00007  METDB-00008  METDB-00009  METDB-00010  ...  \
CC                                                                     ...   
CC_0            0            0            0            0            0  ...   
CC_1            0            0            0            0            0  ...   
CC_2            0            0            0            0            0  ...   
CC_3            0            0            0            0            0  ...   
CC_4            1            0            0            0            0  ...   

      METDB-00476  METDB-00477  METDB-00478  METDB-00479  METDB-00480  \
CC                                                                      
CC_0            0            0            0            0            0   
CC_1            0            0            0            0            0   
CC_2            0            0            0            0            0   
CC_3            0            0            0            0            0   
CC_4            2            0            0            0            0   

      METDB-00481  METDB-00482  METDB-00483  METDB-00484  METDB-00486  
CC                                                                     
CC_0            0            0            0            0            0  
CC_1            0            0            1            0            0  
CC_2            0            0            0            0            0  
CC_3            0            0            0            0            0  
CC_4            0            0            0            0            0  

[5 rows x 455 columns]

In [11]:
df_metdb_target = pd.read_csv("metdb_target_labelOK.csv", sep = ";", header=None)

In [12]:
df_metdb_target.head()

0             1
0   1_Metdb_ID       Trophie
1  METDB-00001  hétérotrophe
2  METDB-00002            CM
3  METDB-00003            CM
4  METDB-00004            CM

In [13]:
df_metdb_target[0] = df_metdb_target[0].drop_duplicates()

In [14]:
len(df_metdb_target[0].unique())

460

In [15]:
mask = df_metdb_target[0].apply(lambda x : x in df_80_85.columns)

In [16]:
mask.value_counts()

True     455
False      9
Name: 0, dtype: int64

In [17]:
df_metdb_target456 = df_metdb_target.loc[mask]

In [18]:
df_metdb_target456.head()

0             1
1  METDB-00001  hétérotrophe
2  METDB-00002            CM
3  METDB-00003            CM
4  METDB-00004            CM
5  METDB-00005            CM

In [19]:
df_metdb_target456_T = df_metdb_target456.T
df_metdb_target456_T

1            2            3            4            5    \
0   METDB-00001  METDB-00002  METDB-00003  METDB-00004  METDB-00005   
1  hétérotrophe           CM           CM           CM           CM   

           6            7            8            9            10   ...  \
0  METDB-00006  METDB-00007  METDB-00008  METDB-00009  METDB-00010  ...   
1  phototrophe           CM           CM           CM          NaN  ...   

           453          454           455          456          457  \
0  METDB-00476  METDB-00477   METDB-00478  METDB-00479  METDB-00480   
1          NaN          NaN  hétérotrophe          NaN          NaN   

           458          459          460           461          463  
0  METDB-00481  METDB-00482  METDB-00483   METDB-00484  METDB-00486  
1  phototrophe          NaN  phototrophe  hétérotrophe           CM  

[2 rows x 455 columns]

In [20]:
#df_metdb_target.drop["1_Metdb_ID"]

In [21]:
df_metdb_target456_T.drop(df_metdb_target456_T.index[[0]], inplace=True)

In [22]:
df_metdb_target456_T.head()

1   2   3   4   5            6   7   8   9    10   ...  453  454  \
1  hétérotrophe  CM  CM  CM  CM  phototrophe  CM  CM  CM  NaN  ...  NaN  NaN   

            455  456  457          458  459          460           461 463  
1  hétérotrophe  NaN  NaN  phototrophe  NaN  phototrophe  hétérotrophe  CM  

[1 rows x 455 columns]

In [23]:
df_metdb_target.dtypes

0    object
1    object
dtype: object

In [24]:
#df_80_85 = df_80_85.append(df_metdb_target)

In [25]:
#Pour ajourter une ligne avec Numpy : 
#array = np.vstack([array, row])

In [26]:
import numpy as np
df_80_85 = np.vstack([df_80_85,df_metdb_target456_T]) #To add target to df

In [27]:
#C'est la même chose que le vstack avec numpy :
#df_80_85_test = np.append([df_80_85],[df_metdb_target456_T])

In [28]:
#del df_80_85_test

In [29]:
import numpy as np
# Total Rows: 
print("{} rows in df_80_85".format(np.shape(df_80_85)[0]))

#Total Columns: 
print("{} columns in df_80_85".format(np.shape(df_80_85)[1]))

1016113 rows in df_80_85
455 columns in df_80_85


In [30]:
#Pour vérifier que le join (vstack) c'est bien passé :
print(df_80_85[1016112])

['hétérotrophe' 'CM' 'CM' 'CM' 'CM' 'phototrophe' 'CM' 'CM' 'CM' nan
 'hétérotrophe' 'CM' 'CM' 'phototrophe' 'phototrophe' nan 'hétérotrophe'
 'hétérotrophe' 'hétérotrophe' 'hétérotrophe' nan 'phototrophe'
 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' 'hétérotrophe'
 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' nan
 nan nan 'hétérotrophe' nan 'CM' 'CM' 'CM' 'CM' 'CM' 'CM' nan
 'hétérotrophe' 'hétérotrophe' 'hétérotrophe' 'hétérotrophe'
 'hétérotrophe' 'CM' 'CM' 'phototrophe' 'phototrophe' 'phototrophe'
 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe'
 'phototrophe' 'CM' nan 'phototrophe' 'phototrophe' nan 'phototrophe'
 'phototrophe' nan nan 'phototrophe' 'phototrophe' 'phototrophe' nan
 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' 'phototrophe' nan
 'phototrophe' 'phototrophe' nan nan nan 'CM' 'CM' 'CM' nan nan nan nan
 nan 'eSNCM' 'phototrophe' 'CM' nan nan 'phototrophe' 'phototrophe'
 'phototrophe' 'phototrophe' na

In [31]:
df_80_85.shape

(1016113, 455)

In [32]:
df_80_85 = df_80_85.T #To transpose rows to columns

In [33]:
df_80_85

array([[1, 1, 3, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       ...,
       [0, 1, 0, ..., 0, 0, 'phototrophe'],
       [0, 0, 0, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM']], dtype=object)

In [34]:
df_80_85.shape

(455, 1016113)

In [35]:
df_80_85[-1]

array([0, 0, 0, ..., 0, 0, 'CM'], dtype=object)

In [36]:
#tesstz = np.nan_to_num(df_80_85, copy=False, nan=0.0)

In [37]:
#pd.DataFrame(df_80_85[:,-1]).fillna(0, inplace=True)

In [38]:
mask = [isinstance(i, str) for i in df_80_85[:,-1]]
df_80_85 = df_80_85[mask,:]
df_80_85

array([[1, 1, 3, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       ...,
       [0, 1, 0, ..., 0, 0, 'phototrophe'],
       [0, 0, 0, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM']], dtype=object)

In [39]:
type(df_80_85[0,-1])

str

In [40]:
#df_80_85 = df_80_85[~mask_nan,:]
#df_80_85

In [41]:
#np.isnan(df_80_85[-1])

In [42]:
df_80_85[0:10,-1]

array(['hétérotrophe', 'CM', 'CM', 'CM', 'CM', 'phototrophe', 'CM', 'CM',
       'CM', 'hétérotrophe'], dtype=object)

In [43]:
df_80_85

array([[1, 1, 3, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       [0, 0, 0, ..., 0, 0, 'CM'],
       ...,
       [0, 1, 0, ..., 0, 0, 'phototrophe'],
       [0, 0, 0, ..., 0, 0, 'hétérotrophe'],
       [0, 0, 0, ..., 0, 0, 'CM']], dtype=object)

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score, mean_squared_error
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) # to avoid deprecation warnings

"""
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
"""

'\nimport plotly.express as px\nimport plotly.graph_objects as go\nimport plotly.io as pio\n'

In [45]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
df_80_85[:,-1] = le.fit_transform(df_80_85[:,-1])

In [46]:
df_80_85

array([[1, 1, 3, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 5],
       [0, 0, 0, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [47]:
df_80_85[:,-1]

array([3, 0, 0, 0, 0, 5, 0, 0, 0, 3, 0, 0, 5, 5, 3, 3, 3, 3, 5, 5, 5, 5,
       5, 3, 5, 5, 5, 5, 5, 3, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 0, 0, 0, 2, 5, 0, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3,
       3, 3, 5, 0, 4, 5, 5, 5, 5, 5, 0, 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 5,
       5, 5, 5, 5, 3, 5, 3, 0, 5, 5, 5, 0, 0, 0, 0, 5, 5, 0, 5, 3, 0, 5,
       5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 3, 5, 5, 5, 5,
       5, 0, 5, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 4, 5,
       0, 5, 5, 2, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3,
       5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 0, 0, 0, 5, 5,
       0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 3,
       5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 3, 5, 5, 5, 3, 5, 3, 3,
       1, 5, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5,

In [48]:
mask_y = [i in [0,3,5] for i in df_80_85[:,-1]]
mask_y[0:10]

[True, True, True, True, True, True, True, True, True, True]

In [49]:
df_80_85 = df_80_85[mask_y,:]

In [50]:
df_80_85

array([[1, 1, 3, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 5],
       [0, 0, 0, ..., 0, 0, 3],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

In [51]:
X = df_80_85[:,:-1]
#X = X.T
y = df_80_85[:,-1]

In [52]:
X.shape

(311, 1016112)

In [53]:
y.shape

(311,)

In [54]:
X

array([[1, 1, 3, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=object)

#To estimated how long processing will take we do some tests with few features
#Then we place result in a graph to see if we need 1 minute or 10 days for all dataset
X1 = X[:,:5]
X2 = X[:,:10]
X3 = X[:,:20]
X4 = X[:,:40]
X5 = X[:,:80]

In [55]:
y = y.astype(int)
y

array([3, 0, 0, 0, 0, 5, 0, 0, 0, 3, 0, 0, 5, 5, 3, 3, 3, 3, 5, 5, 5, 5,
       5, 3, 5, 5, 5, 5, 5, 3, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 0, 0, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 0, 0, 0, 5, 0, 5, 5, 5, 5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3,
       3, 5, 0, 5, 5, 5, 5, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5,
       5, 3, 5, 3, 0, 5, 5, 5, 0, 0, 0, 0, 5, 5, 0, 5, 3, 0, 5, 5, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 3, 5, 5, 5, 5, 5, 0, 5,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 5, 5, 0, 0,
       0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 5, 0, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 5, 0, 0, 0, 5, 5, 0, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 3, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 3, 5, 5, 0, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 3, 5, 5, 5, 3, 5, 3, 3, 5, 0, 0, 0, 0, 0, 0,
       0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,

In [56]:
np.unique(y, return_counts=True)

(array([0, 3, 5]), array([ 86,  41, 184], dtype=int64))

#To estimated how long processing will take we do some tests with few features
#Then we place result in a graph to see if we need 1 minute or 10 days for all dataset
y1 = y[:,:5]
y2 = y[:,:10]
y3 = y[:,:20]
y4 = y[:,:40]
y5 = y[:,:80]

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

sc = StandardScaler()
sc_fit = sc.fit(X_train)
X_train = sc_fit.transform(X_train)
X_test = sc_fit.transform(X_test)

In [58]:
%%time
#New test with cv=5
from sklearn.linear_model import LogisticRegressionCV

lasso = LogisticRegressionCV(penalty='l1', solver="liblinear", cv=5, max_iter = 500) # max_iter = 500  solver="saga"


lasso = lasso.fit(X_train, y_train)
print("On train set accuracy is {}".format(lasso.score(X_train, y_train)))

print("On test set accuracy is {}".format(lasso.score(X_test, y_test)))

On train set accuracy is 1.0
On test set accuracy is 0.8095238095238095
Wall time: 26min 56s


In [59]:
%%time
coef = lasso.coef_

coef = (coef !=0)
n_features_used = np.sum(coef)/3
print(n_features_used)

2203.3333333333335
Wall time: 8 ms


In [61]:
df_coef = pd.DataFrame(lasso.coef_, columns = CC_80_85) #To find columns used to train model

In [62]:
df_coef.head()

CC  CC_0  CC_1  CC_2  CC_3  CC_4  CC_5  CC_6  CC_7  CC_8  CC_9  ...  \
0    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
1    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2    0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

CC  CC_1016102  CC_1016103  CC_1016104  CC_1016105  CC_1016106  CC_1016107  \
0          0.0         0.0         0.0         0.0         0.0         0.0   
1          0.0         0.0         0.0         0.0         0.0         0.0   
2          0.0         0.0         0.0         0.0         0.0         0.0   

CC  CC_1016108  CC_1016109  CC_1016110  CC_1016111  
0          0.0         0.0         0.0         0.0  
1          0.0         0.0         0.0         0.0  
2          0.0         0.0         0.0         0.0  

[3 rows x 1016112 columns]

In [63]:
df_coef.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Columns: 1016112 entries, CC_0 to CC_1016111
dtypes: float64(1016112)
memory usage: 23.3 MB


In [ ]:
"""

%%time
#New test with solver = "sage"
lasso = LogisticRegressionCV(penalty='l1', solver="saga", cv=3, max_iter = 1000) # max_iter = 500  solver="saga"


lasso = lasso.fit(X_train, y_train)
print("On train set accuracy is {}".format(lasso.score(X_train, y_train)))

print("On test set accuracy is {}".format(lasso.score(X_test, y_test)))

"""

In [64]:
df_coef_T = df_coef.T #To transpose columns to rows

In [65]:
df_coef_T.head()

0    1    2
CC                 
CC_0  0.0  0.0  0.0
CC_1  0.0  0.0  0.0
CC_2  0.0  0.0  0.0
CC_3  0.0  0.0  0.0
CC_4  0.0  0.0  0.0

In [ ]:
if df_coef_T.sum == 0  

In [72]:
mask = df_coef_T.sum(axis=1)>0
df_coef_T = df_coef_T.loc[mask]
df_coef_T

0         1         2
CC                                
CC_14      0.0  0.000181  0.000000
CC_29      0.0  0.029934 -0.000391
CC_59      0.0  0.005275  0.000000
CC_151     0.0  0.000003  0.000000
CC_173     0.0  0.005656  0.000000
...        ...       ...       ...
CC_931598  0.0  0.000000  0.001487
CC_931607  0.0  0.000000  0.000280
CC_931615  0.0  0.000000  0.000033
CC_931626  0.0  0.000000  0.000114
CC_984029  0.0  0.000000  0.010940

[3509 rows x 3 columns]

In [74]:
df_coef_T.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3509 entries, CC_14 to CC_984029
Data columns (total 3 columns):
0    3509 non-null float64
1    3509 non-null float64
2    3509 non-null float64
dtypes: float64(3)
memory usage: 109.7+ KB
